# ThermVate — Mosquitto MQTT Broker Config (Docker)
listener 1883
protocol mqtt
allow_anonymous true

listener 9001
protocol websockets
allow_anonymous true

persistence true
persistence_location /mosquitto/data/
autosave_interval 1800

log_type notice
log_type warning
log_type error
connection_messages true
log_timestamp true

max_inflight_messages 20
max_queued_messages 1000

# No bridge loops
bridge_protocol false
